### ISSUE TITLE
The browser IDE doesn't wok

### ISSUE THREAD

**Issue by aifer2007** [nkolban/duktape-esp32#7]
flashing ok, wifi config ok, connect to the browser IDE ok,

But when I click the RUN button , no output in the console area.

And when I click the LOAD button , no response too.

**Comment by nkolban** [comment]
Currently, the console area output is disabled until we can reduce memory consumption in the runtime.  My plan is now to "hide" it in the UI until such time as we can free up some more memory.  The output still remains in the serial log.

**Comment by aifer2007** [comment]
thanks


发自我的 iPhone

**Comment by nkolban** [comment]
Closing believed fixed.
