### ISSUE TITLE
websocket example 

### ISSUE THREAD

**Issue by williamesp2015** [nkolban/duktape-esp32#8]
I would be grateful if you provide websocket example (send and receive binary and text; sync and Asynchronous).
Thank you

**Comment by nkolban** [comment]
To hear is to obey .... have a look at this ...

https://github.com/nkolban/duktape-esp32/blob/master/filesystem/tests/test_ws.js

See if that meets your needs and if not, ping back.

**Comment by williamesp2015** [comment]
Thanks. Sorry I was looking for full example for esp32-snippets.

**Comment by nkolban** [comment]
Howdy ... sorry ... I'm not following.  Have you now found what you are looking for?

**Comment by nkolban** [comment]
Closed believed fixed.
